export const SUPPLIERS: readonly string[] = [
  "Alicia Franssen",
  "Amazon",
  "AXOPAR",
  "Beneteau",
  "Burnewiin",
  "Coval-Group",
  "Epoch Battery",
  "Fathom",
  "Ferretti",
  "Fisheries Supply",
  "Jeff Brown Yachts Kailua Kona",
  "Jeff Brown Yachts Newport Beach",
  "Jeff Brown Yachts Sausalito",
  "Jeff Brown Yachts Seattle",
  "Jeff Brown Yachts West Coast",
  "Jennifer Zender",
  "john smith",
  "Jon Kohler",
  "LandNSea",
  "Lee's Tackle",
  "Lisa Sotelo",
  "Mabru Power Systems",
  "Marine Warehouse Center",
  "Mercury Marine",
  "Mercury Warranty Expense",
  "Off The Hook Yacht Sales OTH",
  "Pacific Trailer",
  "Pardo Yachts",
  "RW Little",
  "SeaWide",
  "Shelter Island Marine Electronics",
  "Sirena Yachts",
  "Supply XYZ",
  "timothy wagoner",
  "Todd Heckel",
  "Volvo",
  "Warranty Account",
  "Webasto",
  "West Marine",
];
